# Generated by Django 4.1.5 on 2023-08-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_rename_total_with_vat_booking_total_price_with_vat'),
        ('management', '0003_alter_invoice_due_date_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('in_stock', 'متوفر'), ('out_of_stock', 'إنتهى المخزون'), ('low', 'منخفض')], default='in_stock', max_length=20)),
                ('stock_number', models.CharField(default='generate_stock_number', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel')),
            ],
        ),
    ]
