# Generated by Django 4.1.5 on 2023-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_department_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
