# Generated by Django 4.1.5 on 2023-08-29 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
