# Generated by Django 4.1.5 on 2023-08-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_expense_created_expense_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='line_total',
        ),
    ]
