# Generated by Django 4.1.5 on 2023-08-10 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200, verbose_name='اسم الفندق')),
                ('city', models.CharField(choices=[('Makkah', 'مكة المكرمة'), ('Madinah', 'المدينة المنورة')], max_length=200, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان')),
                ('tel', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الجوال')),
                ('category', models.IntegerField(choices=[(1, 'نجمة'), (2, 'نجمتان'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم'), (6, 'شقق مخدومة'), (7, 'غير مصنف')], verbose_name='التصنيف')),
                ('Cancellation_policy', models.IntegerField(blank=True, choices=[(1, 'مستردة'), (2, 'غير مستردة')], null=True, verbose_name='سياسة الإلغاء')),
                ('Cancellation_hours', models.IntegerField(blank=True, choices=[(1, '24 ساعة'), (2, '48 ساعة'), (3, '72 ساعة')], null=True, verbose_name='إلغاء الحجز بعد')),
                ('Check_in', models.CharField(blank=True, max_length=100, null=True, verbose_name='سياسة وقت الدخول')),
                ('Check_out', models.CharField(blank=True, max_length=100, null=True, verbose_name='سياسة وقت الخروج')),
                ('nationality', django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name='جنسية الضيوف')),
                ('is_priority', models.BooleanField(default=False, verbose_name='أولوية؟')),
                ('about_hotel', models.TextField(blank=True, null=True, verbose_name='نبذة عن الفندق')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/gallery/', verbose_name='صورة رمزية')),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المالك')),
            ],
            options={
                'ordering': ['-is_priority'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.IntegerField(blank=True, choices=[(1, 'مفردة'), (2, 'ثنائية'), (3, 'ثلاثية'), (4, 'رباعية'), (5, 'خماسية'), (6, 'سداسية')], default=1, verbose_name='نوع الغرفة')),
                ('capacity', models.IntegerField(blank=True, verbose_name='عدد استيعاب الغرفة للأشخاص من هذا النوع')),
                ('Electric', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'تلفزيون'), ('2', 'فرن'), ('3', 'ميكرويف'), ('4', 'غسالة'), ('5', 'مكواة'), ('6', 'غلاية شاهي'), ('7', 'ثلاجة')], max_length=10, null=True, verbose_name='الأجهزة الكهربائية')),
                ('Facilities', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'مطبخ'), ('2', 'غرفة غسيل'), ('3', 'بانيو/ جاكوزي')], max_length=10, null=True, verbose_name='المرافق')),
                ('Services', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'واي فاي'), ('2', 'خدمة الغسيل'), ('3', 'خدمة الغرف')], max_length=10, null=True, verbose_name='الخدمات المجانية')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='اسم الفندق')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=250, verbose_name='الموسم')),
                ('startDate', models.DateField(verbose_name='بداية الموسم')),
                ('year', models.PositiveIntegerField(verbose_name='للعام')),
                ('endDate', models.DateField(verbose_name='نهاية الموسم')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=250, verbose_name='السعر')),
                ('roomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.roomtype', verbose_name='نوع الغرفة')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.season', verbose_name='الموسم')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم الغرفة')),
                ('floor', models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم الطابق')),
                ('capacity', models.IntegerField(blank=True, verbose_name='عدد استيعاب الغرفة للأشخاص من هذا النوع')),
                ('Electric', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'تلفزيون'), ('2', 'فرن'), ('3', 'ميكرويف'), ('4', 'غسالة'), ('5', 'مكواة'), ('6', 'غلاية شاهي'), ('7', 'ثلاجة')], max_length=10, null=True, verbose_name='الأجهزة الكهربائية')),
                ('Facilities', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'مطبخ'), ('2', 'غرفة غسيل'), ('3', 'بانيو/ جاكوزي')], max_length=10, null=True, verbose_name='المرافق')),
                ('Services', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'واي فاي'), ('2', 'خدمة الغسيل'), ('3', 'خدمة الغرف')], max_length=10, null=True, verbose_name='الخدمات المجانية')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'غير مفعلة'), (2, 'متاحة'), (3, 'انتظار'), (4, 'محجوزة')], default=2, verbose_name='حالة الغرفة')),
                ('is_mine', models.BooleanField(default=True, verbose_name='تحت إدارتي؟')),
                ('is_view', models.IntegerField(blank=True, choices=[(1, 'إطلالة كاملة على الحرم'), (2, 'إطلالة جزئية على الحرم'), (3, 'إطلالة على المدينة'), (4, 'غير مطلة')], null=True, verbose_name='الإطلالة')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(verbose_name='سعر الغرفة')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='مالك الغرفة')),
                ('roomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.roomtype', verbose_name='نوع الغرفة')),
            ],
        ),
        migrations.CreateModel(
            name='HotelMultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/hotel_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='اسم الفندق')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HotelLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, verbose_name='Longitude')),
                ('hrm', models.CharField(blank=True, max_length=200, null=True, verbose_name='المسافة عن الحرم')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='اسم الفندق')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم كامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('phone', models.CharField(max_length=255, verbose_name='رقم الهاتف')),
                ('vat', models.FloatField(default=7, verbose_name='ضريبة القيمة المضافة')),
                ('total_with_vat', models.FloatField(default=0, verbose_name='الاجمالي مع القيمة المضافة')),
                ('coupon', models.FloatField(default=1, verbose_name='كوبون خصم')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('proccessed', 'تم الحجز'), ('rejected', 'مرفوض')], default='pending', max_length=50, verbose_name='حالة الطلب')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='الفندق')),
                ('room', models.ManyToManyField(to='dashboard.room', verbose_name='الغرفة')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=250, verbose_name='السعر')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'ملغي'), (2, 'متاح لاستقبال الطلبات'), (3, 'قيد إجراءات التأجير'), (4, 'تم التأجير')], default=2, verbose_name='حالة الغرفة')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='اسم الفندق')),
                ('rooms', models.ManyToManyField(related_name='rooms', to='dashboard.room', verbose_name='الغرف')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.season', verbose_name='الموسم')),
            ],
        ),
    ]
