# Generated by Django 4.1.5 on 2023-03-16 03:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name='جنسية الضيوف'),
        ),
    ]
