# Generated by Django 4.1.5 on 2023-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_booking_email_remove_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('processed', 'تم الحجز'), ('rejected', 'مرفوض')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
    ]
