# Generated by Django 4.1.5 on 2023-03-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hotel_logo_alter_hotel_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery/', verbose_name='صورة رمزية'),
        ),
    ]
