# Generated by Django 4.1.5 on 2023-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_booking_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocation',
            name='hrm',
            field=models.FloatField(blank=True, null=True, verbose_name='المسافة عن الحرم'),
        ),
    ]
