# Generated by Django 4.1.5 on 2023-03-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_hotel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Check_in',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وقت الدخول'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Check_out',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وقت الخروج'),
        ),
    ]
