# Generated by Django 4.1.5 on 2023-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_hotel_check_in_alter_hotel_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
