# Generated by Django 4.1.5 on 2023-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_hotel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
