# Generated by Django 4.1.5 on 2023-08-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_hotellocation_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='dashboard.hotellocation', verbose_name='الموقع'),
        ),
    ]
