# Generated by Django 4.1.5 on 2023-08-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_hotel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotellocation',
            name='hotel',
        ),
    ]
