# Generated by Django 4.1.5 on 2023-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_hotellocation_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotellocation',
            options={'ordering': ['-hrm']},
        ),
        migrations.AddField(
            model_name='booking',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='المستندات'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.IntegerField(choices=[(1, 'ذكر'), (2, 'انثى')], default=1, verbose_name='الجنس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=15, verbose_name='عدد الضيوف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(default=' notes ', verbose_name='ملاحظات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payments_receipts/', verbose_name='ايصال الدفع'),
        ),
    ]
