# Generated by Django 4.1.5 on 2023-03-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_hotel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, verbose_name='الإحداثي X')),
                ('longitude', models.FloatField(blank=True, verbose_name='الإحداثي Y')),
                ('hrm', models.CharField(blank=True, max_length=200, null=True, verbose_name='المسافة عن الحرم')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='اسم الفندق')),
            ],
        ),
    ]
