# Generated by Django 4.1.5 on 2023-08-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_booking_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='اسم وسيلة الدفع')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('merchant_code', models.CharField(max_length=15, verbose_name='رمز التاجر')),
                ('currency', models.CharField(choices=[('SAR', 'SAR'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, verbose_name='العملة')),
                ('status', models.BooleanField(default=False, verbose_name='حالة وسيلة الدفع')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ المغادرة'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ الوصول'),
        ),
    ]
