# Generated by Django 4.1.5 on 2023-08-15 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_paymentmethod_alter_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='hotel',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='الفندق'),
            preserve_default=False,
        ),
    ]
