# Generated by Django 4.1.5 on 2023-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_hotellocation_created_hotellocation_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocation',
            name='latitude',
            field=models.FloatField(blank=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hotellocation',
            name='longitude',
            field=models.FloatField(blank=True, verbose_name='Longitude'),
        ),
    ]
