# Generated by Django 4.1.5 on 2023-08-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_paymentmethod_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(choices=[('active', 'نشطة'), ('inactive', 'معطلة')], max_length=32, verbose_name='حالة وسيلة الدفع'),
        ),
    ]
