# Generated by Django 4.1.5 on 2023-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_paymentmethod_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'ذكر'), ('Female', 'انثى')], default='Male', verbose_name='الجنس'),
        ),
    ]
