# Generated by Django 4.1.5 on 2023-03-18 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_hotelmultipleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelmultipleimage',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='hotelmultipleimage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
