# Generated by Django 4.1.5 on 2023-08-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_booking_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('Male', 'ذكر'), ('Female', 'انثى')], default='Male', max_length=10, verbose_name='الجنس'),
        ),
    ]
