# Generated by Django 4.1.5 on 2023-03-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_hotelmultipleimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Check_in',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سياسة وقت الدخول'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Check_out',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سياسة وقت الخروج'),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(blank=True, choices=[(1, 'مفردة'), (2, 'ثنائية'), (3, 'ثلاثية'), (4, 'رباعية'), (5, 'خماسية'), (6, 'سداسية')], max_length=250, verbose_name='نوع الغرفة')),
                ('NoOfRoom', models.IntegerField(blank=True, verbose_name='عدد الغرف من هذا النوع')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='اسم الفندق')),
            ],
        ),
    ]
