# Generated by Django 4.1.5 on 2023-03-20 13:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_hotel_check_in_alter_hotel_check_out_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='Electric',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'تلفزيون'), ('2', 'فرن'), ('3', 'ميكرويف'), ('4', 'غسالة'), ('5', 'مكواة'), ('6', 'غلاية شاهي'), ('7', 'ثلاجة')], max_length=10, null=True, verbose_name='الأجهزة الكهربائية'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='Facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'مطبخ'), ('2', 'غرفة غسيل'), ('3', 'بانيو/ جاكوزي')], max_length=10, null=True, verbose_name='المرافق'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='Services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'واي فاي'), ('2', 'خدمة الغسيل'), ('3', 'خدمة الغرف')], max_length=10, null=True, verbose_name='الخدمات المجانية'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, verbose_name='عدد استيعاب الأشخاص'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomType',
            field=models.CharField(blank=True, choices=[(1, 'مفردة'), (2, 'ثنائية'), (3, 'ثلاثية'), (4, 'رباعية'), (5, 'خماسية'), (6, 'سداسية')], default=1, max_length=250, verbose_name='نوع الغرفة'),
        ),
    ]
