# Generated by Django 4.1.5 on 2023-08-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.IntegerField(choices=[(100, 'تحويل بنكي'), (200, 'دفع الكتروني'), (300, 'دفع عند الوصول')], default=100, verbose_name='نوع وسيلة الدفع'),
        ),
    ]
