# Generated by Django 4.1.5 on 2023-03-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_roomtype_electric_roomtype_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, verbose_name='عدد استيعاب الغرفة للأشخاص من هذا النوع'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='roomType',
            field=models.IntegerField(blank=True, choices=[(1, 'مفردة'), (2, 'ثنائية'), (3, 'ثلاثية'), (4, 'رباعية'), (5, 'خماسية'), (6, 'سداسية')], default=1, max_length=250, verbose_name='نوع الغرفة'),
        ),
    ]
