# Generated by Django 4.1.5 on 2023-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_paymentmethod_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='merchant_code',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='ipan',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم ألاي بان'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='swifit_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='سويفت كود'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='currency',
            field=models.CharField(blank=True, choices=[('SAR', 'SAR'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, null=True, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.IntegerField(choices=[(100, 'تحويل بنكي'), (200, 'دفع عند الوصول')], default=100, verbose_name='نوع وسيلة الدفع'),
        ),
    ]
