# Generated by Django 4.1.5 on 2023-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(blank=True, choices=[('1', 'غير مفعلة'), ('2', 'متاحة'), ('3', 'انتظار'), ('4', 'محجوزة')], default=1, verbose_name='حالة الغرفة'),
        ),
    ]
