# Generated by Django 4.1.5 on 2023-03-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_room_is_active_room_is_mine_alter_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_mine',
            field=models.BooleanField(default=True, verbose_name='تحت إدارتي؟'),
        ),
    ]
