# Generated by Django 4.1.5 on 2023-08-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_booking_status_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gender',
        ),
    ]
