# Generated by Django 4.1.5 on 2023-03-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_room_is_mine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(blank=True, verbose_name='عدد استيعاب الغرفة للأشخاص من هذا النوع'),
        ),
    ]
