# Generated by Django 4.1.5 on 2023-08-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_booking_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vat',
        ),
        migrations.AddField(
            model_name='hotel',
            name='vat',
            field=models.FloatField(default=7, verbose_name='ضريبة القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
    ]
