# Generated by Django 4.1.5 on 2023-03-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_roomtype_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, verbose_name='عدد استيعاب الغرفة للأشخاص من هذا النوع'),
        ),
    ]
