# Generated by Django 4.1.5 on 2023-08-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_booking_vat_hotel_vat_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vat',
            field=models.FloatField(default=7, verbose_name='ضريبة القيمة المضافة'),
        ),
    ]
