# Generated by Django 4.1.5 on 2023-08-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_booking_vat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='total_with_vat',
            new_name='total_price_with_vat',
        ),
    ]
