# Generated by Django 4.1.5 on 2023-08-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_rename_total_with_vat_request_total_price_with_vat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_with_vat',
            new_name='total_price_with_vat',
        ),
    ]
