# Generated by Django 4.1.5 on 2023-03-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='رقم الطابق'),
        ),
    ]
