# Generated by Django 4.1.5 on 2023-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_rename_total_with_vat_booking_total_price_with_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='roomType',
            field=models.CharField(blank=True, choices=[('single', 'مفردة'), ('double', 'ثنائية'), ('triple', 'ثلاثية'), ('quadruple', 'رباعية'), ('quintuple', 'خماسية'), ('6', 'سداسية')], default='single', max_length=32, verbose_name='نوع الغرفة'),
        ),
    ]
