# Generated by Django 4.1.5 on 2023-09-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_roomtype_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='dashboard.hotellocation', verbose_name='الموقع'),
        ),
    ]
