# Generated by Django 4.1.5 on 2023-03-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد استيعاب الغرفة للأشخاص من هذا النوع'),
        ),
    ]
