# Generated by Django 4.1.5 on 2023-09-03 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellocation',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='الموقع'),
        ),
    ]
