# Generated by Django 4.1.5 on 2023-03-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_room_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, verbose_name='عدد استيعاب الغرفة للأشخاص من هذا النوع'),
            preserve_default=False,
        ),
    ]
