# Generated by Django 4.1.5 on 2023-09-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_hotellocation_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocation',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='dashboard.hotel', verbose_name='الموقع'),
        ),
    ]
