# Generated by Django 4.1.5 on 2023-09-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_hotellocation_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocation',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='dashboard.hotel', verbose_name='الفندق'),
        ),
    ]
