# Generated by Django 4.1.5 on 2023-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_seasonprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='roomType',
            field=models.IntegerField(blank=True, choices=[(1, 'مفردة'), (2, 'ثنائية'), (3, 'ثلاثية'), (4, 'رباعية'), (5, 'خماسية'), (6, 'سداسية')], default=1, verbose_name='نوع الغرفة'),
        ),
    ]
