# Generated by Django 4.1.5 on 2023-03-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
