# Generated by Django 4.1.5 on 2023-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_view',
            field=models.CharField(blank=True, choices=[(1, 'إطلالة كاملة على الحرم'), (2, 'إطلالة جزئية على الحرم'), (3, 'إطلالة على المدينة'), (4, 'غير مطلة')], max_length=250, null=True, verbose_name='مطلة؟'),
        ),
    ]
