# Generated by Django 4.1.5 on 2023-03-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_room_is_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='NoOfRoom',
        ),
    ]
