# Generated by Django 4.1.5 on 2023-04-04 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0041_remove_roomtype_noofroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=250, verbose_name='السعر')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'غير مفعلة'), (2, 'متاحة'), (3, 'انتظار'), (4, 'محجوزة')], default=2, verbose_name='حالة الغرفة')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(null=True, to='dashboard.room', verbose_name='الغرف')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.season', verbose_name='الموسم')),
            ],
        ),
    ]
