# Generated by Django 4.1.5 on 2023-04-04 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_annualrent_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualrent',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='اسم الفندق'),
            preserve_default=False,
        ),
    ]
