# Generated by Django 4.1.5 on 2023-04-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_annualrent_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualrent',
            name='owner',
        ),
    ]
