# Generated by Django 4.1.5 on 2023-04-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_annualrent_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualrent',
            name='rooms',
            field=models.ManyToManyField(related_name='rooms', to='dashboard.room', verbose_name='الغرف'),
        ),
    ]
