# Generated by Django 4.1.5 on 2023-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_annualrent_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualrent',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'ملغي'), (2, 'متاح لاستقبال الطلبات'), (3, 'قيد إجراءات التأجير'), (4, 'تم التأجير')], default=2, verbose_name='حالة الغرفة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_view',
            field=models.IntegerField(blank=True, choices=[(1, 'إطلالة كاملة على الحرم'), (2, 'إطلالة جزئية على الحرم'), (3, 'إطلالة على المدينة'), (4, 'غير مطلة')], null=True, verbose_name='الإطلالة'),
        ),
    ]
