# Generated by Django 4.1.5 on 2023-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_annualrent_status_alter_room_is_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/gallery/', verbose_name='صورة رمزية'),
        ),
    ]
