# Generated by Django 4.1.5 on 2023-06-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_hotel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery/', verbose_name='صورة رمزية'),
        ),
    ]
