# Generated by Django 4.1.5 on 2023-06-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_alter_hotel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Cancellation_hours',
            field=models.IntegerField(blank=True, choices=[(1, '24 ساعة'), (2, '48 ساعة'), (3, '72 ساعة')], null=True, verbose_name='إلغاء الحجز بعد'),
        ),
    ]
