# Generated by Django 4.1.5 on 2023-08-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_hotel_cancellation_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.FloatField()),
                ('total_with_vat', models.FloatField()),
                ('coupon', models.FloatField()),
                ('roomNo', models.IntegerField()),
                ('status', models.CharField(max_length=200, verbose_name=(('PENDING', 'pending'), ('PROCCESSED', 'proccessed'), ('REJECTED', 'rejected')))),
                ('created_at', models.DateTimeField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel')),
            ],
        ),
    ]
