# Generated by Django 4.1.5 on 2023-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(max_length=200, verbose_name=((1, 'في الانتظار'), (0, 'تم الحجز'), (2, 'مرفوض'))),
        ),
    ]
