# Generated by Django 4.1.5 on 2023-08-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.FloatField(verbose_name='كوبون خصم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='الفندق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='roomNo',
            field=models.IntegerField(verbose_name='الغرفة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'في الانتظار'), (0, 'تم الحجز'), (2, 'مرفوض')], verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_with_vat',
            field=models.FloatField(verbose_name='الاجمالي مع القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat',
            field=models.FloatField(verbose_name='ضريبة القيمة المضافة'),
        ),
    ]
