# Generated by Django 4.1.5 on 2023-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_alter_order_coupon_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('proccessed', 'تم الحجز'), ('rejected', 'مرفوض')], max_length=50, verbose_name='حالة الطلب'),
        ),
    ]
