# Generated by Django 4.1.5 on 2023-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_remove_room_owner_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=100, verbose_name='سعر الغرفة'),
            preserve_default=False,
        ),
    ]
