# Generated by Django 4.1.5 on 2023-08-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='roomNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room', verbose_name='الغرفة'),
        ),
    ]
