# Generated by Django 4.1.5 on 2023-08-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_order_roomno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='roomNo',
            new_name='room',
        ),
    ]
