# Generated by Django 4.1.5 on 2023-08-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_rename_roomno_order_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254, verbose_name='البريد الالكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Ali Muhammed Elameen', max_length=255, verbose_name='الاسم كامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+96624331234', max_length=255, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.FloatField(default=1, verbose_name='كوبون خصم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('proccessed', 'تم الحجز'), ('rejected', 'مرفوض')], default='pending', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat',
            field=models.FloatField(default=7, verbose_name='ضريبة القيمة المضافة'),
        ),
    ]
