# Generated by Django 4.1.5 on 2023-08-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_order_email_order_full_name_order_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم كامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('phone', models.CharField(max_length=255, verbose_name='رقم الهاتف')),
                ('vat', models.FloatField(default=7, verbose_name='ضريبة القيمة المضافة')),
                ('total_with_vat', models.FloatField(verbose_name='الاجمالي مع القيمة المضافة')),
                ('coupon', models.FloatField(default=1, verbose_name='كوبون خصم')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('proccessed', 'تم الحجز'), ('rejected', 'مرفوض')], default='pending', max_length=50, verbose_name='حالة الطلب')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hotel', verbose_name='الفندق')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room', verbose_name='الغرفة')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
