# Generated by Django 4.1.5 on 2023-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_booking_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(to='dashboard.room', verbose_name='الغرفة'),
        ),
    ]
