# Generated by Django 4.1.5 on 2023-08-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_season_year_alter_booking_total_with_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(max_length=250, verbose_name='للعام'),
        ),
    ]
