# Generated by Django 4.1.5 on 2023-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_alter_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveIntegerField(verbose_name='للعام'),
        ),
    ]
