# Generated by Django 4.1.5 on 2023-08-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_alter_season_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[(1, 'موسم الحج'), (2, 'موسم رمضان'), (3, 'موسم الزيارة والعمرة')], max_length=250, verbose_name='الموسم'),
        ),
    ]
