# Generated by Django 4.1.5 on 2023-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_alter_season_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(max_length=250, verbose_name='الموسم'),
        ),
    ]
